#!/usr/bin/env ruby
old_verbose, $VERBOSE = $VERBOSE, nil
begin
  require File.expand_path("../../lib/hurley/test/server", __FILE__)
ensure
  $VERBOSE = old_verbose
end

port = 4000
if found = ARGV.index("-p")
  port = ARGV[found + 1].to_i
end

Hurley::Live.start_server(
  :port => port,
  :ssl_key => ENV["HURLEY_SSL_KEY"],
  :ssl_file => ENV["HURLEY_SSL_FILE"],
)
